// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6uEuFdHfPnROJeso8A-PsTZPAjsVMcaU',
    appId: '1:25562651801:android:007aeb4ae1c65171672c08',
    messagingSenderId: '25562651801',
    projectId: 'job-task-project-46da6',
    storageBucket: 'job-task-project-46da6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV5QiVPoniRyozO3FvuSpRS1ecQClxSLs',
    appId: '1:25562651801:ios:8341dffb50cfcf60672c08',
    messagingSenderId: '25562651801',
    projectId: 'job-task-project-46da6',
    storageBucket: 'job-task-project-46da6.firebasestorage.app',
    androidClientId: '25562651801-31m9ffdhtqnt30f0mlntfs7vhpf8m4d1.apps.googleusercontent.com',
    iosClientId: '25562651801-cdv0h83dcaf8mavt1jjnciehvhn5cgm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.bdCallingTask',
  );
}
